document.getElementById("hamburger").addEventListener("click",function(){
    document.getElementsByTagName("rect")[0].classList.toggle("top");
    document.getElementsByTagName("rect")[1].classList.toggle("middle");
    document.getElementsByTagName("rect")[2].classList.toggle("bottom");
    if($("#menu").is(":visible")){
        $("#menu").hide();
    }else{
        $("#menu").show();
    }
});
